/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as DoctorsSlugRouteImport } from './routes/doctors.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsSlugRoute = DoctorsSlugRouteImport.update({
  id: '/doctors/$slug',
  path: '/doctors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/doctors': typeof DoctorsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/doctors/$slug' | '/doctors/' | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/doctors/$slug' | '/doctors' | '/services'
  id: '__root__' | '/' | '/doctors/$slug' | '/doctors/' | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorsSlugRoute: typeof DoctorsSlugRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$slug': {
      id: '/doctors/$slug'
      path: '/doctors/$slug'
      fullPath: '/doctors/$slug'
      preLoaderRoute: typeof DoctorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorsSlugRoute: DoctorsSlugRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
